import "dotenv/config";
import mongoose from "mongoose";
import Exercise from "../models/Exercise.js";
import connectDB from "../config/db.js";

// Fake Cloudinary base URL for seed images
const IMG = (slug) =>
  `https://res.cloudinary.com/demo/image/upload/taekwondo/${slug}.jpg`;

const exercises = [
  // ── TECHNIQUE ──────────────────────────────────────────────────────────────
  {
    name: "Ap Chagi – Front Kick",
    slug: "ap-chagi-front-kick",
    shortDescription:
      "Kick de base en taekwondo, frappe avec le ballon du pied.",
    description:
      "L'Ap Chagi est le coup de pied frontal fondamental du taekwondo. Il cible le niveau moyen et développe l'extension de la hanche et la puissance de la jambe.",
    category: "technique",
    level: 1,
    focus: ["hips", "quads"],
    equipment: ["none"],
    tags: ["kick", "basic", "front"],
    image: {
      url: IMG("ap-chagi-front-kick"),
      publicId: "taekwondo/ap-chagi-front-kick",
      width: 800,
      height: 600,
      alt: "Ap Chagi front kick",
    },
    instructions: [
      "Adopte ta garde de combat.",
      "Lève le genou de la jambe frappante haut devant toi.",
      "Étends la jambe en propulsant le ballon du pied vers l'avant.",
      "Rétracte rapidement la jambe après l'impact.",
      "Repose le pied et reprends ta garde.",
    ],
    commonMistakes: [
      "Ne pas remonter le genou assez haut",
      "Pencher le buste vers l'arrière",
    ],
    safetyNotes: ["Étire les ischio-jambiers avant de pratiquer."],
    durationSecDefault: 40,
    repsDefault: 10,
    restSecDefault: 20,
    caloriesEstimate: 5,
    isFeatured: true,
    isPublished: true,
  },
  {
    name: "Dollyo Chagi – Roundhouse Kick",
    slug: "dollyo-chagi-roundhouse-kick",
    shortDescription: "Coup de pied circulaire iconique du taekwondo.",
    description:
      "Le Dollyo Chagi est le coup de pied le plus utilisé en compétition. Il se délivre en arc de cercle et cible la tête ou le tronc.",
    category: "technique",
    level: 2,
    focus: ["hips", "core"],
    equipment: ["none"],
    tags: ["kick", "roundhouse", "competition"],
    image: {
      url: IMG("dollyo-chagi-roundhouse-kick"),
      publicId: "taekwondo/dollyo-chagi-roundhouse-kick",
      width: 800,
      height: 600,
      alt: "Dollyo Chagi roundhouse kick",
    },
    instructions: [
      "Pivote sur la jambe d'appui en tournant le talon vers la cible.",
      "Soulève le genou de côté à hauteur de cible.",
      "Déploie la jambe en fouettant vers la cible avec le cou-de-pied.",
      "Rétracte la jambe puis reprends ta garde.",
    ],
    commonMistakes: [
      "Ne pas pivoter suffisamment sur le pied d'appui",
      "Frapper avec les orteils",
    ],
    safetyNotes: ["Renforce les chevilles avant de pratiquer à haute vitesse."],
    durationSecDefault: 45,
    repsDefault: 8,
    restSecDefault: 20,
    caloriesEstimate: 6,
    isFeatured: true,
    isPublished: true,
  },
  {
    name: "Yeop Chagi – Side Kick",
    slug: "yeop-chagi-side-kick",
    shortDescription:
      "Coup de pied latéral puissant avec le tranchant du pied.",
    description:
      "Le Yeop Chagi se délivre sur le côté du corps avec le tranchant ou le talon. Il est redoutable pour tenir l'adversaire à distance.",
    category: "technique",
    level: 2,
    focus: ["hips", "glutes"],
    equipment: ["none"],
    tags: ["kick", "side", "power"],
    image: {
      url: IMG("yeop-chagi-side-kick"),
      publicId: "taekwondo/yeop-chagi-side-kick",
      width: 800,
      height: 600,
      alt: "Yeop Chagi side kick",
    },
    instructions: [
      "Pivote de 90° pour présenter le flanc à la cible.",
      "Lève le genou vers la poitrine en fléchissant la hanche.",
      "Pousse la jambe horizontalement vers la cible avec le talon.",
      "Rétracte et replace le pied.",
    ],
    commonMistakes: [
      "Casser le bassin en arrière",
      "Frapper avec la plante au lieu du talon",
    ],
    safetyNotes: [
      "Travaille la souplesse de la hanche latérale régulièrement.",
    ],
    durationSecDefault: 45,
    repsDefault: 8,
    restSecDefault: 20,
    caloriesEstimate: 6,
    isFeatured: false,
    isPublished: true,
  },
  {
    name: "Dwi Chagi – Back Kick",
    slug: "dwi-chagi-back-kick",
    shortDescription: "Coup de pied arrière dévastateur avec le talon.",
    description:
      "Le Dwi Chagi utilise la force du talon propulsée vers l'arrière. La rotation du corps génère une puissance maximale.",
    category: "technique",
    level: 3,
    focus: ["glutes", "core"],
    equipment: ["none"],
    tags: ["kick", "back", "power"],
    image: {
      url: IMG("dwi-chagi-back-kick"),
      publicId: "taekwondo/dwi-chagi-back-kick",
      width: 800,
      height: 600,
      alt: "Dwi Chagi back kick",
    },
    instructions: [
      "À partir de ta garde, tourne les épaules et la tête vers l'arrière.",
      "Ramène le genou vers la poitrine puis projette le talon en arrière.",
      "Maintiens l'alignement hanche–talon.",
      "Reprends ta garde après l'impact.",
    ],
    commonMistakes: [
      "Ne pas regarder la cible avant de frapper",
      "Plier le buste vers l'avant",
    ],
    safetyNotes: ["Effectue la rotation lentement avant d'accélérer."],
    durationSecDefault: 45,
    repsDefault: 6,
    restSecDefault: 25,
    caloriesEstimate: 7,
    isFeatured: false,
    isPublished: true,
  },
  {
    name: "Naeryo Chagi – Axe Kick",
    slug: "naeryo-chagi-axe-kick",
    shortDescription: "Coup de pied en hache du dessus vers le bas.",
    description:
      "Le Naeryo Chagi monte la jambe tendue puis la fait redescendre en hache sur la cible. Nécessite une grande souplesse des ischio-jambiers.",
    category: "technique",
    level: 4,
    focus: ["hamstrings", "hips"],
    equipment: ["none"],
    tags: ["kick", "axe", "flexibility"],
    image: {
      url: IMG("naeryo-chagi-axe-kick"),
      publicId: "taekwondo/naeryo-chagi-axe-kick",
      width: 800,
      height: 600,
      alt: "Naeryo Chagi axe kick",
    },
    instructions: [
      "Lève la jambe tendue au maximum vers le haut.",
      "Redescends la jambe en hache sur la cible (crâne ou épaule).",
      "Contrôle la descente pour ne pas te blesser.",
    ],
    commonMistakes: [
      "Fléchir le genou à la montée",
      "Manquer de souplesse et forcer",
    ],
    safetyNotes: [
      "Ne pratique pas sans échauffement approfondi des ischio-jambiers.",
    ],
    durationSecDefault: 40,
    repsDefault: 6,
    restSecDefault: 30,
    caloriesEstimate: 6,
    isFeatured: false,
    isPublished: true,
  },
  // ── POOMSAE ────────────────────────────────────────────────────────────────
  {
    name: "Taegeuk Il Jang – Poomsae 1",
    slug: "taegeuk-il-jang",
    shortDescription: "Premier poomsae de la série Taegeuk, symbole du ciel.",
    description:
      "Le Taegeuk Il Jang est la première forme officielle de la WTF. Il enseigne la marche avant, le bloc bas, le coup de pied frontal et le coup de poing.",
    category: "poomsae",
    level: 1,
    focus: ["full-body", "coordination"],
    equipment: ["none"],
    tags: ["poomsae", "taegeuk", "beginner", "wt"],
    image: {
      url: IMG("taegeuk-il-jang"),
      publicId: "taekwondo/taegeuk-il-jang",
      width: 800,
      height: 600,
      alt: "Taegeuk Il Jang",
    },
    instructions: [
      "Commence en position Charyot (garde à vous).",
      "Effectue 18 mouvements selon le diagramme en forme de I.",
      "Chaque séquence : pas en Ap Seogi + bloc ou frappe.",
      "Termine en Baero (position initiale).",
    ],
    commonMistakes: [
      "Oublier les transitions de pied",
      "Manquer de puissance dans les blocs",
    ],
    safetyNotes: [],
    durationSecDefault: 60,
    restSecDefault: 30,
    caloriesEstimate: 8,
    isFeatured: true,
    isPublished: true,
  },
  {
    name: "Taegeuk Ee Jang – Poomsae 2",
    slug: "taegeuk-ee-jang",
    shortDescription: "Deuxième poomsae Taegeuk, symbole de la joie.",
    description:
      "Le Taegeuk Ee Jang introduit la posture Ap Kubi (avant profond) et de nouveaux blocs. Il renforce la stabilité et l'enchaînement des techniques.",
    category: "poomsae",
    level: 2,
    focus: ["full-body", "balance"],
    equipment: ["none"],
    tags: ["poomsae", "taegeuk", "intermediate"],
    image: {
      url: IMG("taegeuk-ee-jang"),
      publicId: "taekwondo/taegeuk-ee-jang",
      width: 800,
      height: 600,
      alt: "Taegeuk Ee Jang",
    },
    instructions: [
      "Commence en Charyot et salut.",
      "Enchaine 18 mouvements avec la posture Ap Kubi sur les pas avant.",
      "Introduit le bloc médian extérieur (Momtong Bakat Makki).",
      "Termine en Baero.",
    ],
    commonMistakes: [
      "Trop courte la posture Ap Kubi",
      "Bras de bloc non aligné",
    ],
    safetyNotes: [],
    durationSecDefault: 60,
    restSecDefault: 30,
    caloriesEstimate: 8,
    isFeatured: false,
    isPublished: true,
  },
  // ── SPARRING ───────────────────────────────────────────────────────────────
  {
    name: "Footwork basique – In & Out",
    slug: "footwork-basic-in-out",
    shortDescription:
      "Déplacements d'entrée et de sortie de la distance de combat.",
    description:
      "Ce drill de déplacement entraîne le pratiquant à contrôler la distance en combat. L'objectif est de rentrer vite, frapper et ressortir hors de portée.",
    category: "sparring",
    level: 1,
    focus: ["footwork", "agility"],
    equipment: ["none"],
    tags: ["sparring", "footwork", "drill"],
    image: {
      url: IMG("footwork-basic-in-out"),
      publicId: "taekwondo/footwork-basic-in-out",
      width: 800,
      height: 600,
      alt: "Footwork In & Out drill",
    },
    instructions: [
      "Prends ta garde de combat à distance de sécurité.",
      "Effectue un pas avant rapide (entrée).",
      "Frappe immédiatement (kick ou punch simulé).",
      "Recule d'un pas (sortie) en reprenant ta garde.",
      "Répète en variant le côté d'attaque.",
    ],
    commonMistakes: [
      "Télégraphier le mouvement d'entrée",
      "Ne pas reprendre la garde après la sortie",
    ],
    safetyNotes: ["Pratique lentement avant d'accélérer."],
    durationSecDefault: 30,
    repsDefault: 15,
    restSecDefault: 15,
    caloriesEstimate: 8,
    isFeatured: false,
    isPublished: true,
  },
  {
    name: "Combinaison 1-2 Punch + Dollyo",
    slug: "combo-punch-dollyo",
    shortDescription:
      "Enchaînement poing avant, poing arrière puis Dollyo Chagi.",
    description:
      "Combinaison classique de combat : deux coups de poing pour distraire puis Dollyo Chagi pour scorer. Travaille le timing et la fluidité entre membres supérieurs et inférieurs.",
    category: "sparring",
    level: 2,
    focus: ["coordination", "speed"],
    equipment: ["none"],
    tags: ["sparring", "combo", "competition"],
    image: {
      url: IMG("combo-punch-dollyo"),
      publicId: "taekwondo/combo-punch-dollyo",
      width: 800,
      height: 600,
      alt: "Combo punch + Dollyo Chagi",
    },
    instructions: [
      "Depuis ta garde, frappe avec le poing avant (jab).",
      "Enchaîne immédiatement avec le poing arrière (cross).",
      "Pivote sur le pied avant et déclenche un Dollyo Chagi de la jambe arrière.",
      "Rétracte et reprends ta garde.",
    ],
    commonMistakes: [
      "Pause entre les poings et le kick",
      "Perdre l'équilibre au pivot",
    ],
    safetyNotes: [],
    durationSecDefault: 30,
    repsDefault: 8,
    restSecDefault: 20,
    caloriesEstimate: 9,
    isFeatured: true,
    isPublished: true,
  },
  // ── MOBILITY ───────────────────────────────────────────────────────────────
  {
    name: "Hip Opener Flow",
    slug: "hip-opener-flow",
    shortDescription:
      "Séquence d'ouverture de la hanche pour kicks plus hauts.",
    description:
      "Cette routine mobilise la hanche en rotation interne et externe, indispensable pour performer des coups de pied au-dessus de la ceinture.",
    category: "mobility",
    level: 1,
    focus: ["hips"],
    equipment: ["none"],
    tags: ["mobility", "hips", "warm-up"],
    image: {
      url: IMG("hip-opener-flow"),
      publicId: "taekwondo/hip-opener-flow",
      width: 800,
      height: 600,
      alt: "Hip opener stretch",
    },
    instructions: [
      "Debout, effectue 10 cercles de hanche dans chaque sens.",
      "Passe en fente avant basse, genou arrière au sol.",
      "Ouvre la hanche avant vers l'extérieur (pigeon debout) 30 s.",
      "Répète de l'autre côté.",
    ],
    commonMistakes: ["Cambrer excessivement le bas du dos"],
    safetyNotes: ["Arrête si douleur dans l'aine."],
    durationSecDefault: 60,
    restSecDefault: 15,
    caloriesEstimate: 3,
    isFeatured: true,
    isPublished: true,
  },
  {
    name: "Shoulder Mobility Circle",
    slug: "shoulder-mobility-circle",
    shortDescription: "Rotation complète des épaules pour libérer les blocs.",
    description:
      "Mobilise l'articulation gléno-humérale dans toute son amplitude pour des blocs efficaces et sans tension.",
    category: "mobility",
    level: 1,
    focus: ["shoulders"],
    equipment: ["none"],
    tags: ["mobility", "shoulders", "warm-up"],
    image: {
      url: IMG("shoulder-mobility-circle"),
      publicId: "taekwondo/shoulder-mobility-circle",
      width: 800,
      height: 600,
      alt: "Shoulder mobility circles",
    },
    instructions: [
      "Bras tendus sur les côtés, effectue de grands cercles vers l'avant 10x.",
      "Inverse le sens pour 10 cercles vers l'arrière.",
      "Croise les bras devant la poitrine et serre 5 s, relâche.",
    ],
    commonMistakes: ["Cercles trop petits", "Hausser les épaules"],
    safetyNotes: [],
    durationSecDefault: 45,
    restSecDefault: 10,
    caloriesEstimate: 2,
    isFeatured: false,
    isPublished: true,
  },
  // ── STRENGTH ───────────────────────────────────────────────────────────────
  {
    name: "Squat Jump",
    slug: "squat-jump",
    shortDescription: "Squat explosif pour développer la puissance des jambes.",
    description:
      "Le squat jump développe la force explosive des quadriceps, fessiers et mollets, directement transférable à la hauteur et la vitesse des kicks.",
    category: "strength",
    level: 2,
    focus: ["quads", "glutes"],
    equipment: ["none"],
    tags: ["strength", "plyometric", "legs"],
    image: {
      url: IMG("squat-jump"),
      publicId: "taekwondo/squat-jump",
      width: 800,
      height: 600,
      alt: "Squat jump exercise",
    },
    instructions: [
      "Pieds écartés largeur d'épaules, descends en squat profond.",
      "Explose vers le haut en sautant le plus haut possible.",
      "Réceptionne en douceur en fléchissant les genoux.",
      "Enchaîne immédiatement le squat suivant.",
    ],
    commonMistakes: ["Genoux rentrés à la réception", "Descente insuffisante"],
    safetyNotes: ["Ne pratique pas si douleur aux genoux."],
    durationSecDefault: 30,
    repsDefault: 12,
    restSecDefault: 30,
    caloriesEstimate: 10,
    isFeatured: false,
    isPublished: true,
  },
  {
    name: "Plank Hold",
    slug: "plank-hold",
    shortDescription: "Gainage abdominal statique pour un core solide.",
    description:
      "Le plank renforce les abdominaux profonds, les lombaires et les fessiers. Un core solide améliore l'équilibre et la puissance de tous les coups de pied.",
    category: "strength",
    level: 1,
    focus: ["core"],
    equipment: ["none"],
    tags: ["strength", "core", "static"],
    image: {
      url: IMG("plank-hold"),
      publicId: "taekwondo/plank-hold",
      width: 800,
      height: 600,
      alt: "Plank hold position",
    },
    instructions: [
      "Appuie-toi sur les avant-bras et les orteils.",
      "Aligne tête, épaules, bassin et talons.",
      "Contracte le core et retiens la respiration 2 s toutes les 10 s.",
      "Maintiens la position selon le temps prescrit.",
    ],
    commonMistakes: ["Chute du bassin", "Remonter les fesses trop haut"],
    safetyNotes: [],
    durationSecDefault: 45,
    restSecDefault: 20,
    caloriesEstimate: 4,
    isFeatured: false,
    isPublished: true,
  },
  {
    name: "Push Up",
    slug: "push-up",
    shortDescription: "Pompe classique pour renforcer pectoraux et triceps.",
    description:
      "Les pompes développent la force des membres supérieurs et du gainage, utile pour la puissance des coups de poing et des blocs.",
    category: "strength",
    level: 1,
    focus: ["chest", "triceps", "core"],
    equipment: ["none"],
    tags: ["strength", "upper-body", "classic"],
    image: {
      url: IMG("push-up"),
      publicId: "taekwondo/push-up",
      width: 800,
      height: 600,
      alt: "Push up position",
    },
    instructions: [
      "Mains à largeur d'épaules, corps en gainage.",
      "Descends jusqu'à ce que la poitrine frôle le sol.",
      "Pousse les bras en extension complète.",
      "Répète sans laisser le bassin chuter.",
    ],
    commonMistakes: ["Chute du bassin", "Coudes trop écartés"],
    safetyNotes: [],
    durationSecDefault: 30,
    repsDefault: 15,
    restSecDefault: 30,
    caloriesEstimate: 6,
    isFeatured: false,
    isPublished: true,
  },
  {
    name: "Burpees",
    slug: "burpees",
    shortDescription:
      "Exercice full-body explosif pour l'endurance et la force.",
    description:
      "Les burpees combinent squat, plank, pompe et saut vertical. Ils développent la condition physique générale indispensable pour tenir en combat.",
    category: "strength",
    level: 3,
    focus: ["full-body", "conditioning"],
    equipment: ["none"],
    tags: ["strength", "conditioning", "plyometric"],
    image: {
      url: IMG("burpees"),
      publicId: "taekwondo/burpees",
      width: 800,
      height: 600,
      alt: "Burpee exercise",
    },
    instructions: [
      "Debout, descends en squat et pose les mains au sol.",
      "Saute les pieds en arrière en position planche.",
      "Effectue une pompe ce n'est pas obligatoire mais recommandé.",
      "Ramène les pieds vers les mains d'un saut.",
      "Saute verticalement en levant les bras.",
    ],
    commonMistakes: [
      "Sauter les pieds en arrière un par un",
      "Ne pas verrouiller le core en planche",
    ],
    safetyNotes: ["Évite si douleur au poignet."],
    durationSecDefault: 30,
    repsDefault: 10,
    restSecDefault: 40,
    caloriesEstimate: 12,
    isFeatured: false,
    isPublished: true,
  },
  // ── FLEXIBILITY ────────────────────────────────────────────────────────────
  {
    name: "Hamstring Stretch",
    slug: "hamstring-stretch",
    shortDescription: "Étirement des ischio-jambiers pour kicks plus hauts.",
    description:
      "Étirement essentiel pour tout pratiquant de taekwondo. Des ischio-jambiers souples permettent d'exécuter les kicks au-dessus de la ceinture sans risque.",
    category: "flexibility",
    level: 1,
    focus: ["hamstrings"],
    equipment: ["none"],
    tags: ["flexibility", "stretch", "cool-down"],
    image: {
      url: IMG("hamstring-stretch"),
      publicId: "taekwondo/hamstring-stretch",
      width: 800,
      height: 600,
      alt: "Hamstring stretch",
    },
    instructions: [
      "Assis au sol, jambes tendues devant toi.",
      "Penche le buste en avant en gardant le dos droit.",
      "Attrape tes pieds ou tes chevilles et maintiens 30 s.",
      "Répète 3 fois.",
    ],
    commonMistakes: ["Arrondir le dos", "Forcer la descente avec les bras"],
    safetyNotes: ["Ne jamais forcer dans la douleur."],
    durationSecDefault: 60,
    restSecDefault: 10,
    caloriesEstimate: 2,
    isFeatured: false,
    isPublished: true,
  },
  {
    name: "Lunge Stretch",
    slug: "lunge-stretch",
    shortDescription: "Fente en flexion pour assouplir le flexor de la hanche.",
    description:
      "La fente basse est l'étirement incontournable du psoas et du droit antérieur. Essentiel pour l'amplitude des coups de pied et la posture de combat.",
    category: "flexibility",
    level: 1,
    focus: ["hip-flexors", "quads"],
    equipment: ["none"],
    tags: ["flexibility", "stretch", "hips"],
    image: {
      url: IMG("lunge-stretch"),
      publicId: "taekwondo/lunge-stretch",
      width: 800,
      height: 600,
      alt: "Lunge stretch position",
    },
    instructions: [
      "Avance un grand pas en avant, genou arrière au sol.",
      "Pousse le bassin vers le bas et l'avant.",
      "Maintiens 30 s en respirant profondément.",
      "Change de côté.",
    ],
    commonMistakes: [
      "Genou avant qui dépasse la pointe du pied",
      "Cambrer excessivement",
    ],
    safetyNotes: [],
    durationSecDefault: 60,
    restSecDefault: 10,
    caloriesEstimate: 2,
    isFeatured: false,
    isPublished: true,
  },
];

const run = async () => {
  await connectDB();

  for (const ex of exercises) {
    await Exercise.updateOne({ slug: ex.slug }, { $set: ex }, { upsert: true });
  }

  console.log(`✅ ${exercises.length} exercises seeded`);
  await mongoose.disconnect();
};

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
